version: '3'

services:

  masbcpp:
    image: "shapespace/masbcpp"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9988:8888"
    volumes:
      - ./notebooks:/home/analytics/notebooks
      - .:/tmp/stuff/masbcpp
      - ./tmp/cnpy:/tmp/stuff/cnpy