# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/stuff/masbcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/stuff/masbcpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/stuff/masbcpp/CMakeFiles /tmp/stuff/masbcpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/stuff/masbcpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named masbcpp

# Build rule for target.
masbcpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 masbcpp
.PHONY : masbcpp

# fast build rule for target.
masbcpp/fast:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/build
.PHONY : masbcpp/fast

#=============================================================================
# Target rules for targets named compute_ma

# Build rule for target.
compute_ma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compute_ma
.PHONY : compute_ma

# fast build rule for target.
compute_ma/fast:
	$(MAKE) -f CMakeFiles/compute_ma.dir/build.make CMakeFiles/compute_ma.dir/build
.PHONY : compute_ma/fast

#=============================================================================
# Target rules for targets named compute_normals

# Build rule for target.
compute_normals: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compute_normals
.PHONY : compute_normals

# fast build rule for target.
compute_normals/fast:
	$(MAKE) -f CMakeFiles/compute_normals.dir/build.make CMakeFiles/compute_normals.dir/build
.PHONY : compute_normals/fast

#=============================================================================
# Target rules for targets named simplify

# Build rule for target.
simplify: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplify
.PHONY : simplify

# fast build rule for target.
simplify/fast:
	$(MAKE) -f CMakeFiles/simplify.dir/build.make CMakeFiles/simplify.dir/build
.PHONY : simplify/fast

src/compute_ma.o: src/compute_ma.cpp.o

.PHONY : src/compute_ma.o

# target to build an object file
src/compute_ma.cpp.o:
	$(MAKE) -f CMakeFiles/compute_ma.dir/build.make CMakeFiles/compute_ma.dir/src/compute_ma.cpp.o
.PHONY : src/compute_ma.cpp.o

src/compute_ma.i: src/compute_ma.cpp.i

.PHONY : src/compute_ma.i

# target to preprocess a source file
src/compute_ma.cpp.i:
	$(MAKE) -f CMakeFiles/compute_ma.dir/build.make CMakeFiles/compute_ma.dir/src/compute_ma.cpp.i
.PHONY : src/compute_ma.cpp.i

src/compute_ma.s: src/compute_ma.cpp.s

.PHONY : src/compute_ma.s

# target to generate assembly for a file
src/compute_ma.cpp.s:
	$(MAKE) -f CMakeFiles/compute_ma.dir/build.make CMakeFiles/compute_ma.dir/src/compute_ma.cpp.s
.PHONY : src/compute_ma.cpp.s

src/compute_ma_processing.o: src/compute_ma_processing.cpp.o

.PHONY : src/compute_ma_processing.o

# target to build an object file
src/compute_ma_processing.cpp.o:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/src/compute_ma_processing.cpp.o
.PHONY : src/compute_ma_processing.cpp.o

src/compute_ma_processing.i: src/compute_ma_processing.cpp.i

.PHONY : src/compute_ma_processing.i

# target to preprocess a source file
src/compute_ma_processing.cpp.i:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/src/compute_ma_processing.cpp.i
.PHONY : src/compute_ma_processing.cpp.i

src/compute_ma_processing.s: src/compute_ma_processing.cpp.s

.PHONY : src/compute_ma_processing.s

# target to generate assembly for a file
src/compute_ma_processing.cpp.s:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/src/compute_ma_processing.cpp.s
.PHONY : src/compute_ma_processing.cpp.s

src/compute_normals.o: src/compute_normals.cpp.o

.PHONY : src/compute_normals.o

# target to build an object file
src/compute_normals.cpp.o:
	$(MAKE) -f CMakeFiles/compute_normals.dir/build.make CMakeFiles/compute_normals.dir/src/compute_normals.cpp.o
.PHONY : src/compute_normals.cpp.o

src/compute_normals.i: src/compute_normals.cpp.i

.PHONY : src/compute_normals.i

# target to preprocess a source file
src/compute_normals.cpp.i:
	$(MAKE) -f CMakeFiles/compute_normals.dir/build.make CMakeFiles/compute_normals.dir/src/compute_normals.cpp.i
.PHONY : src/compute_normals.cpp.i

src/compute_normals.s: src/compute_normals.cpp.s

.PHONY : src/compute_normals.s

# target to generate assembly for a file
src/compute_normals.cpp.s:
	$(MAKE) -f CMakeFiles/compute_normals.dir/build.make CMakeFiles/compute_normals.dir/src/compute_normals.cpp.s
.PHONY : src/compute_normals.cpp.s

src/compute_normals_processing.o: src/compute_normals_processing.cpp.o

.PHONY : src/compute_normals_processing.o

# target to build an object file
src/compute_normals_processing.cpp.o:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/src/compute_normals_processing.cpp.o
.PHONY : src/compute_normals_processing.cpp.o

src/compute_normals_processing.i: src/compute_normals_processing.cpp.i

.PHONY : src/compute_normals_processing.i

# target to preprocess a source file
src/compute_normals_processing.cpp.i:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/src/compute_normals_processing.cpp.i
.PHONY : src/compute_normals_processing.cpp.i

src/compute_normals_processing.s: src/compute_normals_processing.cpp.s

.PHONY : src/compute_normals_processing.s

# target to generate assembly for a file
src/compute_normals_processing.cpp.s:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/src/compute_normals_processing.cpp.s
.PHONY : src/compute_normals_processing.cpp.s

src/io.o: src/io.cpp.o

.PHONY : src/io.o

# target to build an object file
src/io.cpp.o:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/src/io.cpp.o
.PHONY : src/io.cpp.o

src/io.i: src/io.cpp.i

.PHONY : src/io.i

# target to preprocess a source file
src/io.cpp.i:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/src/io.cpp.i
.PHONY : src/io.cpp.i

src/io.s: src/io.cpp.s

.PHONY : src/io.s

# target to generate assembly for a file
src/io.cpp.s:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/src/io.cpp.s
.PHONY : src/io.cpp.s

src/simplify.o: src/simplify.cpp.o

.PHONY : src/simplify.o

# target to build an object file
src/simplify.cpp.o:
	$(MAKE) -f CMakeFiles/simplify.dir/build.make CMakeFiles/simplify.dir/src/simplify.cpp.o
.PHONY : src/simplify.cpp.o

src/simplify.i: src/simplify.cpp.i

.PHONY : src/simplify.i

# target to preprocess a source file
src/simplify.cpp.i:
	$(MAKE) -f CMakeFiles/simplify.dir/build.make CMakeFiles/simplify.dir/src/simplify.cpp.i
.PHONY : src/simplify.cpp.i

src/simplify.s: src/simplify.cpp.s

.PHONY : src/simplify.s

# target to generate assembly for a file
src/simplify.cpp.s:
	$(MAKE) -f CMakeFiles/simplify.dir/build.make CMakeFiles/simplify.dir/src/simplify.cpp.s
.PHONY : src/simplify.cpp.s

src/simplify_processing.o: src/simplify_processing.cpp.o

.PHONY : src/simplify_processing.o

# target to build an object file
src/simplify_processing.cpp.o:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/src/simplify_processing.cpp.o
.PHONY : src/simplify_processing.cpp.o

src/simplify_processing.i: src/simplify_processing.cpp.i

.PHONY : src/simplify_processing.i

# target to preprocess a source file
src/simplify_processing.cpp.i:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/src/simplify_processing.cpp.i
.PHONY : src/simplify_processing.cpp.i

src/simplify_processing.s: src/simplify_processing.cpp.s

.PHONY : src/simplify_processing.s

# target to generate assembly for a file
src/simplify_processing.cpp.s:
	$(MAKE) -f CMakeFiles/masbcpp.dir/build.make CMakeFiles/masbcpp.dir/src/simplify_processing.cpp.s
.PHONY : src/simplify_processing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... masbcpp"
	@echo "... compute_ma"
	@echo "... compute_normals"
	@echo "... rebuild_cache"
	@echo "... simplify"
	@echo "... src/compute_ma.o"
	@echo "... src/compute_ma.i"
	@echo "... src/compute_ma.s"
	@echo "... src/compute_ma_processing.o"
	@echo "... src/compute_ma_processing.i"
	@echo "... src/compute_ma_processing.s"
	@echo "... src/compute_normals.o"
	@echo "... src/compute_normals.i"
	@echo "... src/compute_normals.s"
	@echo "... src/compute_normals_processing.o"
	@echo "... src/compute_normals_processing.i"
	@echo "... src/compute_normals_processing.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/simplify.o"
	@echo "... src/simplify.i"
	@echo "... src/simplify.s"
	@echo "... src/simplify_processing.o"
	@echo "... src/simplify_processing.i"
	@echo "... src/simplify_processing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

